nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
    paths:
        '^/api/login_check':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['POST']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            